### ISSUE TITLE
Standardises pipeline deliverables

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/hermes#8]
We need to standardise the output categories of each pipline e.g. files, metrics, softwares and references.

This would allow processes such as:
`category -> microservice..n -> delivery_endpoint`

For example
`files -> hermes -> cg -> housekeeper`
`metrics -> hermes -> cg -> cg_delivery_report -> housekeeper -> scout`
`metrics -> hermes -> cg -> vougue`
`metrics|softwares|references -> hermes -> cg -> pipeline_delivery_report -> housekeeper -> scout`

In file `<case>_deliverables.yaml`:
```
files:
  - format: <fastq|bam|cram|bcf|vcf|meta|"whatever_makes_sense"> "#String|required"
    id: <sample_id|case_id|project_id> "#String|required"
    path:  </a/absolute/path/to/analysis_file> "#String|required"
    path_index: </a/path/to/analysis_file.index_suffix> "#String|optional"
    step:  <process_that_controls_generation_of_file> "#String|required"
    tag:  <file_tag> "#String|optional"
  - format: bam
    id: sample_1
    path: /mip_analysis/sample_1/bwa_mem/sample_1.bam
    path_index: /mip_analysis/sample_1/bwa_mem/sample_1.bam.bai
    step: gatk_baserecalibration
    tag: igv_bam
metrics:
  - id: <sample_id|case_id|project_id> "#String|required"
    input: <source_used_to_generate_metric_from> "#String|required"
    name: <read_duplicates> "#String|required"
    software: <generator_of_metric> "#String|required"
    step: <process_that_controls_generation_of_metric> "#String|required"
    value: <value_of_metric> "#required"
  - id: sample_1
    input: /mip_analysis/sample_1/bwa_mem/sample_1.bam
    name: pf_reads_aligned
    software: alignmentsummarymetrics "#String|required"
    step: picardtools_collectmultiplemetrics
    value: 100000
softwares:
  - name: <software> "#String|required"
    path: <path_to_software> "#String|required"
    version: <software_version> "#required"
  - name: bwa
    path: docker.io/clinicalgenomics/bwa:0.7.17
    version: 0.7.17
references:
  - name: <reference_name> "#String|required"
    path: <path_to_reference> "#String|required"
    version: <reference_version> "#required"
  - name: nist_call_set_bed
    path: /a/absolute/path/to/references_9.0/grch37_nist_hg001_-na12878_v2.19-.bed
    version: na12878_v2.19
```
